// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayrollManager.Domain.Data;

#nullable disable

namespace PayrollManager.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723210632_AddEmployeeAddressAndSsn")]
    partial class AddEmployeeAddressAndSsn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("PayrollManager.Domain.Models.AuditLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationVersion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.CompanySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultHoursPerPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MedicarePercent")
                        .HasColumnType("TEXT");

                    b.Property<int>("PayPeriodsPerYear")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReceivesFullFutaCredit")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SocialSecurityPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SuiRatePercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SuiWageBase")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CompanySettings");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.DeductionLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPreTax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PayStubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PayStubId");

                    b.ToTable("DeductionLines");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.EarningLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Hours")
                        .HasColumnType("TEXT");

                    b.Property<int>("PayStubId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PayStubId");

                    b.ToTable("EarningLines");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualSalary")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultHoursPerPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilingStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HealthInsurancePerPeriod")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IlAdditionalAllowances")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IlBasicAllowances")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHourly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OtherDeductionsPerPeriod")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PreTax401kPercent")
                        .HasColumnType("TEXT");

                    b.Property<string>("SsnEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("SsnLast4")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("W4Deductions")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("W4DependentsAndOtherCredits")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("W4ExtraWithholding")
                        .HasColumnType("TEXT");

                    b.Property<bool>("W4MultipleJobsChecked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("W4OnFile")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("W4OtherIncome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.PayRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalculationEngineVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalculationHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PayDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PostedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VoidReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VoidedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status", "PayDate");

                    b.ToTable("PayRuns");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.PayStub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EmployerFuta")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmployerMedicare")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmployerSocialSecurity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmployerSui")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossPay")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetPay")
                        .HasColumnType("TEXT");

                    b.Property<int>("PayRunId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PostTaxDeductions")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PreTax401kDeduction")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxFederal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxMedicare")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxSocialSecurity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxState")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("YtdGross")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("YtdNet")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("YtdTaxes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PayRunId");

                    b.ToTable("PayStubs");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.TaxLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PayStubId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxableAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PayStubId");

                    b.ToTable("TaxLines");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.DeductionLine", b =>
                {
                    b.HasOne("PayrollManager.Domain.Models.PayStub", "PayStub")
                        .WithMany("DeductionLines")
                        .HasForeignKey("PayStubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayStub");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.EarningLine", b =>
                {
                    b.HasOne("PayrollManager.Domain.Models.PayStub", "PayStub")
                        .WithMany("EarningLines")
                        .HasForeignKey("PayStubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayStub");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.PayStub", b =>
                {
                    b.HasOne("PayrollManager.Domain.Models.Employee", "Employee")
                        .WithMany("PayStubs")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollManager.Domain.Models.PayRun", "PayRun")
                        .WithMany("PayStubs")
                        .HasForeignKey("PayRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayRun");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.TaxLine", b =>
                {
                    b.HasOne("PayrollManager.Domain.Models.PayStub", "PayStub")
                        .WithMany("TaxLines")
                        .HasForeignKey("PayStubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayStub");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.Employee", b =>
                {
                    b.Navigation("PayStubs");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.PayRun", b =>
                {
                    b.Navigation("PayStubs");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.PayStub", b =>
                {
                    b.Navigation("DeductionLines");

                    b.Navigation("EarningLines");

                    b.Navigation("TaxLines");
                });
#pragma warning restore 612, 618
        }
    }
}
