// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayrollManager.Domain.Data;

#nullable disable

namespace PayrollManager.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260119200000_AddDeductionAndTaxLines")]
    partial class AddDeductionAndTaxLines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            // This is a simplified version - EF Core will regenerate this on next migration
#pragma warning restore 612, 618
        }
    }
}
