// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayrollManager.Domain.Data;

#nullable disable

namespace PayrollManager.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("PayrollManager.Domain.Models.CompanySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultHoursPerPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FederalTaxPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MedicarePercent")
                        .HasColumnType("TEXT");

                    b.Property<int>("PayPeriodsPerYear")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SocialSecurityPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StateTaxPercent")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CompanySettings");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.EarningLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Hours")
                        .HasColumnType("TEXT");

                    b.Property<int>("PayStubId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PayStubId");

                    b.ToTable("EarningLines");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualSalary")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HealthInsurancePerPeriod")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHourly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OtherDeductionsPerPeriod")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PreTax401kPercent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.PayRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PayDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PayRuns");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.PayStub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GrossPay")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetPay")
                        .HasColumnType("TEXT");

                    b.Property<int>("PayRunId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PostTaxDeductions")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PreTax401kDeduction")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxFederal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxMedicare")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxSocialSecurity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxState")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("YtdGross")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("YtdNet")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("YtdTaxes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PayRunId");

                    b.ToTable("PayStubs");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.DeductionLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPreTax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PayStubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PayStubId");

                    b.ToTable("DeductionLines");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.TaxLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PayStubId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxableAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PayStubId");

                    b.ToTable("TaxLines");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.EarningLine", b =>
                {
                    b.HasOne("PayrollManager.Domain.Models.PayStub", "PayStub")
                        .WithMany("EarningLines")
                        .HasForeignKey("PayStubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayStub");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.PayStub", b =>
                {
                    b.HasOne("PayrollManager.Domain.Models.Employee", "Employee")
                        .WithMany("PayStubs")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollManager.Domain.Models.PayRun", "PayRun")
                        .WithMany("PayStubs")
                        .HasForeignKey("PayRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayRun");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.Employee", b =>
                {
                    b.Navigation("PayStubs");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.PayRun", b =>
                {
                    b.Navigation("PayStubs");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.DeductionLine", b =>
                {
                    b.HasOne("PayrollManager.Domain.Models.PayStub", "PayStub")
                        .WithMany("DeductionLines")
                        .HasForeignKey("PayStubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayStub");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.TaxLine", b =>
                {
                    b.HasOne("PayrollManager.Domain.Models.PayStub", "PayStub")
                        .WithMany("TaxLines")
                        .HasForeignKey("PayStubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayStub");
                });

            modelBuilder.Entity("PayrollManager.Domain.Models.PayStub", b =>
                {
                    b.Navigation("DeductionLines");

                    b.Navigation("EarningLines");

                    b.Navigation("TaxLines");
                });
#pragma warning restore 612, 618
        }
    }
}
